#!/bin/bash
# ----------------------------------------------------------
#title           :hostname_change 
#description     :This script is used to update centos hostname from dpa1 to iad1  
#author          :Jason Wang 
#email           :jw7698@att.com
#date            :20141017
#version         :0.1
#usage           :1. login to server
#                :2. bash <(wget -qO - https://raw.githubusercontent.com/jason75023/LTMI/master/PSL/hostname_change)
# ----------------------------------------------------------


sed -i.bak 's/dpa/iad/' /etc/sysconfig/network

sed -i.bak 's/dpa/iad/' /etc/hosts


read -p "Enter hostname > " h
hostname $h

sed -i.bak 's/dpa/iad/' /etc/motd

/etc/init.d/network restart
