#!/bin/bash
# ----------------------------------------------------------
#title           :hostname_change 
#description     :This script is used to update centos hostname from dpa1 to iad1  
#author          :Jason Wang 
#email           :jw7698@att.com
#date            :20141017
#version         :0.1
#usage           :hostname_change (returns either exit 0 or 2)
# ----------------------------------------------------------

#sed -i.bak 's/dpa/iad/' /etc/sysconfig/network

#sed -i.bak 's/dpa/iad/' /etc/hosts

echo "enter hostname info \n"
read -p "Enter hostname > " h

#hostname $h

#sed -i.bak 's/dpa/iad/' /etc/motd

#/etc/init.d/network restart
