#!/bin/bash
#
# Script to perform jave heap size increase and javaheap dump setup 
# Make sure standalone.conf.new with latest config info is under /opt/jboss-as-7.1.3.Final/bin
#
stopjboss() {
/etc/init.d/jbossas7 stop 
return 
}

configchange() {
cd /opt/jboss-as-7.1.3.Final/bin
cp -p standalone.conf standalone.conf.`date +%Y%m%d`
cp -p standalone.conf.new standalone.conf
return 
}

configfallback() {
cd /opt/jboss-as-7.1.3.Final/bin
cp -p standalone.conf.`date +%Y%m%d` standalone.conf
return 
} 

startjboss() {
/etc/init.d/jbossas7 start 
return 
}
#
# MAIN program
#
IFS='
'
MENU="
Stop traffic jboss process 
increase java heap size and enable java heap dump 
fallback java config 
Start traffic jboss process
Exit/Stop
"
PS3='Select task:'
select m1 in $MENU
do
case $REPLY in
1) stopjboss;;
2) configchange;;
3) configfallback;;
4) startjboss;;
5) exit 0 ;;
esac
done
